name: Render Neural Canvas

on:
  schedule:
    # Runs every hour to keep the canvas alive
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 100 # Fetch enough history for context

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests svgwrite

      - name: Render the Neural Canvas
        run: python ./render_engine.py ${{ secrets.GITHUB_TOKEN }} anubhab-m02

      - name: Update README metadata
        run: |
          TIMESTAMP=$(TZ="Asia/Kolkata" date)
          COMMIT_MSG=$(git log -1 --pretty=%s | sed 's/[<>`&]/\\&/g') # Sanitize commit message
          sed -i "s|<!--timestamp-->|$TIMESTAMP|g" README.md
          sed -i "s|<!--status-->|🟢 Synchronized|g" README.md
          sed -i "s|<!--latest_commit-->|$COMMIT_MSG|g" README.md

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add neural_canvas.svg README.md
          if ! git diff --staged --quiet; then
            git commit -m "chore: render new state of neural canvas"
            git push
          else
            echo "Canvas state is current. No changes to commit."
          fi
